### ISSUE TITLE
animals

### ISSUE THREAD

**Issue by Nekuza** [Nekuza/gamejam8-2304#8]
animals can be picked up and dropped anywhere to act as a tower

## animal types
- [ ] cattle
- [ ] sheep
- [ ] goat
- [ ] wolf
- [ ] eagle

## TODO
- [x] animals spawn random in their areas
- [ ] unique stats per animal
- [x] turrets deployable by player

**Comment by Nekuza** [comment]
if you touched all animals the game could end
